#!/usr/bin/env bash
#Configures ngnix and redirects so /redirect_me is redirected to another page
#redirection must say "301 Moved Permanently"

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" |sudo tee /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx start
