#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page

sudo apt-get update
sudo apt-get install -y nginx

#Redirection script to google's homepage as an example
echo "Hello World!" | sudo tee /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Custom error page 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# restart the ngnix to take new changes using code below
sudo service nginx restart
