#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update -y
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

# Giving read write execute command to user in this directory
sudo chmod -R 755 /var/www

# The initial index page for a basic site
echo 'Hello World!' |sudo tee  /var/www/html/index.html

# Establishes the page with a 404 response
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# Redirection for a single page(/redirect_me) and adding the header to reveal
# the hostname
new_string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Adding the redirection page for 404 error code
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# After all restart nginx or if possible the server itself to apply updates
sudo service nginx restart
