#!/usr/bin/env bash
# A bash script to install and configure HAProxy on lb-01 server 1
# Haproxy configuration to send traffic to both web servers
# Using the roundrobin algorithm method for load balancers
# Check that your HAProxy can be managed via an init script
# Install then configure Haproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# Edit your config file
server_config=\
"
frontend  eddiema.tech-frontend
        bind *:80
        mode http
        default_backend eddiema.tech-backend
backend eddiema.tech-backend
        balance roundrobin
        server 140006-web-01 52.86.110.26:80 check
        server 140006-web-02 34.207.237.154:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
